"""Type stub for ivy.ivy_ast module-level globals."""

from typing import Any, Optional

lf_counter: int
reference_lineno: Optional[int]
always_clone_with_fresh_id: bool

class ExtractDef:
    with_args: int
    def __init__(self, *args: Any) -> None: ...

class Atom:
    def __init__(self, name: str) -> None: ...

class Sig:
    def add_symbol(self, name: str, sort: Any) -> None: ...

sig: Sig

class ObjectDecl: ...
class _DeclBase:
    args: list[Any]
    def defines(self) -> list[Any]: ...
    name: str
    lineno: int
    def __init__(self, *args: Any) -> None: ...

class ActionDecl(_DeclBase): ...
class TypeDecl(_DeclBase): ...
class DefinitionDecl(_DeclBase): ...
class PropertyDecl(_DeclBase): ...
class AxiomDecl(_DeclBase): ...
class ConjectureDecl(_DeclBase): ...
class IsolateDecl(_DeclBase): ...
class ModuleDecl(_DeclBase): ...
class AliasDecl(_DeclBase): ...
class DerivedDecl(_DeclBase): ...
class InterpretDecl(_DeclBase): ...
class SchemaDecl(_DeclBase): ...
class TheoremDecl(_DeclBase): ...
class DestructorDecl(_DeclBase): ...
class ConstructorDecl(_DeclBase): ...
class ConstantDecl(_DeclBase): ...
class InstantiateDecl(_DeclBase): ...
class VariantDecl(_DeclBase): ...
class MixinDecl(_DeclBase): ...
class ExportDecl(_DeclBase): ...
class ImportDecl(_DeclBase): ...
class NativeDecl(_DeclBase): ...
class AttributeDecl(_DeclBase): ...
class EnumeratedSort(_DeclBase): ...
class MixinAfterDef: ...
class MixinImplementDef: ...
