"""Type stub for ivy.ivy_utils module-level globals."""

from typing import Any, Dict, Optional

filename: Optional[str]
ivy_language_version: str

class SourceFile:
    def __init__(self, path: str) -> None: ...
    def __enter__(self) -> "SourceFile": ...
    def __exit__(self, *args: Any) -> None: ...

class ErrorList(Exception):
    errors: list[Any]

class IvyError(Exception):
    def __init__(self, node: Any, msg: str) -> None: ...

def get_std_include_dir() -> str: ...
def get_string_version() -> str: ...
def set_parameters(params: Dict[str, str]) -> None: ...
