"""Backward-compat shim."""

from ivy_lsp.infra.observability import *  # noqa: F401,F403
from ivy_lsp.infra.observability import (  # noqa: F401
    DebugTracer,
    DedupFilter,
    LogCategory,
    LogEvent,
    LspLogHandler,
    SessionEventLogger,
    SessionJsonLogHandler,
    StructuredLogAdapter,
    ToolTraceContext,
    _log_session_event,
    _read_session_file,
    _workspace_hash,
    call_context,
    describe_logging_config,
    enable_package_instrumentation,
    ensure_call_id,
    get_call_id,
    get_error_count,
    get_logger,
    get_session_id,
    get_session_logger,
    get_tracer,
    init_tracer,
    install_session_jsonl_handler,
    instrument_function,
    instrument_module_functions,
    log_phase,
    reset_session_cache,
    reset_session_logger,
    resolve_session_log_dir,
    timed_phase,
    trace_tool,
)
